# Generated by Django 5.0.7 on 2024-08-06 06:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_stores_chaireview'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='chai_variety',
            field=models.ManyToManyField(related_name='stores', to='firstapp.chaivariety'),
        ),
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certify_number', models.CharField(max_length=50)),
                ('issued_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('validity', models.DateTimeField()),
                ('chai', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certify', to='firstapp.chaivariety')),
            ],
        ),
    ]
